---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springci/github-release-notes-generator-ci-image
    tag: master
inputs:
- name: git-repo
outputs:
- name: release-git-repo
- name: built-artifact
params:
  GITHUB_USERNAME:
  GITHUB_TOKEN:
caches:
- path: maven
run:
  path: git-repo/ci/scripts/release.sh
