---
platform: linux
inputs:
- name: git-repo
outputs:
- name: release-git-repo
- name: built-artifact
params:
  GITHUB_USERNAME:
  GITHUB_TOKEN:
caches:
- path: maven
run:
  path: git-repo/ci/scripts/release.sh
