resource_types:
- name: github-release
  type: registry-image
  source:
    repository: concourse/github-release-resource
    tag: 1.7.2
resources:
- name: git-repo
  type: git
  icon: github
  source:
    uri: https://github.com/spring-io/github-changelog-generator
    username: ((github-username))
    password: ((github-ci-release-token))
    branch: main
    ignore_paths: ["ci/images/*"]
- name: ci-images-git-repo
  type: git
  icon: github
  source:
    uri: https://github.com/spring-io/github-changelog-generator
    branch: main
    paths: ["ci/images/*"]
- name: ci-image
  type: docker-image
  icon: docker
  source:
    repository: springci/github-changelog-generator-ci
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: main
- name: github-release
  type: github-release
  icon: briefcase-download
  source:
    owner: spring-io
    repository: github-changelog-generator
    access_token: ((github-ci-release-token))
jobs:
- name: build-ci-images
  plan:
  - get: ci-images-git-repo
    trigger: true
  - put: ci-image
    params:
      build: ci-images-git-repo/ci/images
      dockerfile: ci-images-git-repo/ci/images/ci-image/Dockerfile
- name: build
  public: true
  plan:
  - get: ci-image
  - get: git-repo
    trigger: true
  - do:
    - task: build
      image: ci-image
      file: git-repo/ci/tasks/build.yml
- name: release
  plan:
  - get: ci-image
  - get: git-repo
    passed: [build]
    trigger: false
  - do:
    - task: release
      image: ci-image
      file: git-repo/ci/tasks/release.yml
      params:
        GITHUB_USERNAME: ((github-username))
        GITHUB_TOKEN: ((github-ci-release-token))
  - put: git-repo
    params:
      repository: release-git-repo
  - put: github-release
    params:
      name: built-artifact/tag
      tag: built-artifact/tag
      body: built-artifact/changelog.md
      globs:
      - built-artifact/github-changelog-generator.jar
groups:
- name: "builds"
  jobs:
  - build
- name: "releases"
  jobs:
  - release
- name: "ci-images"
  jobs:
  - build-ci-images
