resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/spring-io/github-release-notes-generator
    username: ((github-username))
    password: ((github-password))
    branch: master
    ignore_paths: ["ci/images/*"]
- name: ci-images-git-repo
  type: git
  source:
    uri: https://github.com/spring-io/github-release-notes-generator
    branch: master
    paths: ["ci/images/*"]
- name: github-release-notes-generator-ci-image
  type: docker-image
  source:
    repository: springci/github-release-notes-generator-ci-image
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: master
- name: github-release-notes-generator-image
  type: docker-image
  source:
    repository: springio/github-release-notes-generator
    username: ((docker-hub-username))
    password: ((docker-hub-password))
- name: github-release
  type: github-release
  source:
    owner: spring-io
    repository: github-release-notes-generator
    access_token: ((github-ci-release-token))
jobs:
- name: build-github-release-notes-generator-ci-image
  plan:
  - get: ci-images-git-repo
    trigger: true
  - put: github-release-notes-generator-ci-image
    params:
      build: ci-images-git-repo/ci/images
      dockerfile: ci-images-git-repo/ci/images/github-release-notes-generator-ci-image/Dockerfile
- name: build
  plan:
  - get: git-repo
    trigger: true
  - task: build
    file: git-repo/ci/tasks/build.yml
  - put: github-release-notes-generator-image
    params:
      build: .
      dockerfile: git-repo/Dockerfile
      tag: built-artifact/version
      build_args:
        root: git-repo
        jar:  built-artifact/github-release-notes-generator.jar
- name: release
  plan:
  - get: git-repo
    passed: [build]
    trigger: false
  - task: release
    file: git-repo/ci/tasks/release.yml
    params:
      GITHUB_USERNAME: ((github-username))
      GITHUB_TOKEN: ((github-ci-release-token))
  - put: git-repo
    params:
      repository: release-git-repo
  - put: github-release-notes-generator-image
    params:
      build: .
      dockerfile: git-repo/Dockerfile
      tag: built-artifact/version
      build_args:
        root: git-repo
        jar:  built-artifact/github-release-notes-generator.jar
  - put: github-release
    params:
      name: built-artifact/tag
      tag: built-artifact/tag
      body: built-artifact/release-notes.md
      globs:
      - built-artifact/github-release-notes-generator.jar
groups:
- name: "Code"
  jobs:
  - build
  - release
- name: "CI Images"
  jobs:
  - build-github-release-notes-generator-ci-image
